### ISSUE TITLE
Windows 10 right click context actions not working

### ISSUE THREAD

**Issue by TerraTech** [tonystark93/URL-shortener-extension#3] opened 2022-08-18 18:53 UTC
Versions:
- Chrome:  104.0.5112.81
- URL Shortener: 14.0.0
- Windows 10 Pro 21H1 (19043.1889)

Neither of the right click context actions are working.  I have tried it with both 'bit.ly' and 'tinyurl.com'.

I was trying to shorten a file link:
https://github.com/koalaman/shellcheck/releases/download/v0.7.1/shellcheck-v0.7.1.linux.x86_64.tar.xz

If I click the toolbar extension icon, it will shorten the current page.

**Comment by tonystark93** [comment] 2022-09-06 16:36
@TerraTech  Thanks for reporting the issue!
The issue is fixed in this [PR](https://github.com/tonystark93/URL-shortener-extension/pull/4) 
The updated version is available in the chrome store.

**Closed as completed by tonystark93** 2022-09-06 16:36 UTC
